@echo off
setlocal
cd /d "%~dp0"

echo.
echo  PIC Dashboard - Publishing to GitHub...
echo.

REM OneDrive sync can leave a stale lock behind after an interrupted git run
if exist ".git\index.lock" (
    echo  Clearing stale git lock...
    del /f /q ".git\index.lock" >nul 2>&1
    if exist ".git\index.lock" (
        echo.
        echo  COULD NOT REMOVE .git\index.lock
        echo  Close any open git tools / editors, pause OneDrive sync, then retry.
        goto :end
    )
)

echo  Checking for remote changes...
git fetch origin main
if errorlevel 1 goto :fetchfailed

REM feeds.json is generated by the Actions workflow, never edited by hand.
REM Always defer to the remote copy so it can't cause a merge conflict.
git checkout origin/main -- feeds.json >nul 2>&1

echo  Staging changes...
git add -A
if errorlevel 1 goto :failed

REM "git diff --cached --quiet" returns 1 when there ARE staged changes
git diff --cached --quiet
if errorlevel 1 (
    git commit -m "Dashboard update"
    if errorlevel 1 goto :failed
    echo  Committed.
) else (
    echo  Nothing new to commit - pushing any existing commits.
)

echo  Syncing with remote...
git pull --rebase origin main
if errorlevel 1 goto :rebasefailed

echo  Pushing...
git push origin main
if errorlevel 1 goto :pushfailed

echo.
echo  Published. Live at:
echo  https://investmentcollective.github.io/pundicci/
echo  GitHub Pages takes about a minute to rebuild.
goto :end

:fetchfailed
echo.
echo  Could not reach GitHub.
echo  Check your internet connection. If that's fine, the token may have
echo  expired - run auth-github.bat to set a new one.
goto :end

:rebasefailed
echo.
echo  Could not merge the remote changes automatically.
echo  Nothing has been published. To undo the half-finished merge, run:
echo.
echo      git rebase --abort
echo.
echo  Then ask for help before trying again.
goto :end

:failed
echo.
echo  STOPPED - could not stage or commit.
echo  NOTHING has been published.
goto :end

:pushfailed
echo.
echo  Push was rejected. Run this script once more - it re-syncs first
echo  and will usually go through on the second attempt.
echo  If it keeps failing, the token may have expired - run auth-github.bat.
goto :end

:end
echo.
pause
